"""empty message

Revision ID: 7e3b0a57807d
Revises: dbfa2327dc4d
Create Date: 2021-05-31 09:37:27.248806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3b0a57807d'
down_revision = 'dbfa2327dc4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context', sa.Column('status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('context', 'status')
    # ### end Alembic commands ###
