"""empty message

Revision ID: 90e135b5b09f
Revises: 9f404796b7db
Create Date: 2021-05-30 15:59:13.356935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e135b5b09f'
down_revision = '9f404796b7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'apply', ['applyId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apply', type_='unique')
    # ### end Alembic commands ###
