"""empty message

Revision ID: dbfa2327dc4d
Revises: 90e135b5b09f
Create Date: 2021-05-30 16:02:58.473069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfa2327dc4d'
down_revision = '90e135b5b09f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply', sa.Column('content', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apply', 'content')
    # ### end Alembic commands ###
